name: 1.0.0.$(rev:r)
variables: 
- name: Project.Path
  value: $(Build.SourcesDirectory)/**/PolyhydraGames.MonoGame.csproj
- name: BuildConfiguration
  value: Release
- name: Nuspec.ServiceId
  value: 015fc12f-cd63-4ab4-8d6a-dc889e53bf70
trigger:
  branches:
    include:
    - refs/heads/main

jobs:
- job: Phase_1 
  cancelTimeoutInMinutes: 1
  pool:
    name: Default
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: dotnet build 
    inputs:
      projects: '$(Project.Path)'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '$(Project.Path)' 
      versioningScheme: 'byBuildNumber'
      arguments: '-c $(BuildConfiguration)' 
  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      feedPublish: '$(Nuspec.ServiceId)'
      allowPackageConflicts: false
